### ISSUE TITLE
Dubbio su protocollo pubblico di detection e parcheggio

### ISSUE THREAD

**Issue by ale-ben** [sacerdot/Emerging2223Project#1]
https://github.com/sacerdot/Emerging2223Project/blob/22e6e8276dbb21e9f9c10679ecc2dbac4dd36f4c/README.md?plain=1#L67
https://github.com/sacerdot/Emerging2223Project/blob/22e6e8276dbb21e9f9c10679ecc2dbac4dd36f4c/README.md?plain=1#L68

In questi due messaggi inviati dal detect all'ambiente non viene specificato in che cella la macchina sta parcheggiando (o liberando).

L'ambiente deve tenere traccia dell'ultima chiamata ad isFree per ogni automobile e considerare quella cella quando riceve park e leve oppure possiamo implementare i messaggi come segue:
- `{park, PID, X, Y, Ref}`
- `{leave, PID, X, Y, Ref}`

**Comment by sacerdot** [comment]
Chiuso (revisione 1.1):
 {park, PID, Ref} cambiato in {park, PID, X, Y, Ref} closes Issue #1. L'informazione poteva essere ricavata dall'ambient memorizzandola a partire dal precedente messaggio che verificava se il posteggio fosse vuoto o meno. Tuttavia, non essendoci un Ref condiviso, poteva essere ritornata un'informazione non correlata nel caso di perdita di messaggi.
