### ISSUE TITLE
Protocollo per friendship dovrebbe fornire sia PID state che PID friendship

### ISSUE THREAD

**Issue by ale-ben** [sacerdot/Emerging2223Project#2]
Dato che il protocollo di gossiping prevede di comunicare con l'attore state tramite `notifyStatus` https://github.com/sacerdot/Emerging2223Project/blob/7a25f89f7b6d2fe9eeb97329bc8b3df043f929db/README.md?plain=1#L84

e che il protocollo di friendship prevede la comunicazione tra attori friendship tramite `getFriends`
https://github.com/sacerdot/Emerging2223Project/blob/7a25f89f7b6d2fe9eeb97329bc8b3df043f929db/README.md?plain=1#L55

Sarebbe ottimale poter implementare la lista di PID restituita tramite  `myFriends` (`PIDLIST`) come tuple di tipo `{PIDF, PIDS}`,
dove `PIDF` è il PID dell'attore Friendship e `PIDS` il PID dell'attore State del veicolo.
https://github.com/sacerdot/Emerging2223Project/blob/7a25f89f7b6d2fe9eeb97329bc8b3df043f929db/README.md?plain=1#L56

**Comment by sacerdot** [comment]
Nuova versione 1.2 delle spec che accoglie la proposta.
